### ISSUE TITLE
Document that some systems only have docker compose and docker-compose will fail

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#164] opened 2022-08-18 18:21 UTC
See https://github.com/suborbital/docs/pull/155#discussion_r943837606

**Comment by flaki** [comment] 2022-09-07 14:31
I think this is a duplicate of #159 - se the more detailed description there. I just reopened that issue and will close this as a duplicate, feel free to correct me if that's not right.

Laura if #155 fixed this (or the issue mentioned above) feel free to close that one as fixed!

**Closed by flaki** 2022-09-07 14:31 UTC
Labels: documentation
